services:
  weaviate:
    image: semitechnologies/weaviate:1.31.0
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-ollama"
      DEFAULT_VECTORIZER_MODULE: "text2vec-ollama"
      CLUSTER_HOSTNAME: "node1"
      ENABLE_SINGLE_NODE: "true"
      TEXT2VEC_OLLAMA_URL: "http://host.docker.internal:11434"  # connect Ollama running on host

